[build]
  publish = "dist"
  command = "mkdir -p public/fonts && curl --fail $FONTS_URL_1 --output public/fonts/ClanWebPro-News.woff && curl --fail $FONTS_URL_2 --output public/fonts/ClanWebPro-Bold.woff && curl --fail $FONTS_URL_3 --output public/fonts/SourceSerifPro-Regular.woff && curl --fail $FONTS_URL_4 --output public/fonts/SourceSerifPro-Bold.woff && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200