[build]
  publish = "dist"
  command = "curl --fail $FONTS_URL --output fonts.zip && unzip -j fonts.zip -d src/fonts && rm fonts.zip && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200